# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages


pages:    # Nom à utiliser
  tags:
    - shell
  rules:   # Bloc  facultatif : ça permet de déployer la doc que si on a pushé sur la branche master
    - if: $CI_COMMIT_BRANCH == "master"
  script:   # Le dossier html qui défini le site web doit se trouver à la racine du working directory et s'appeller public. Ici, on l'a déjà généré avant donc on a juste à copier
    - cp -r /stck/lbernard/MOLA/Dev/DOCUMENTATION/html public
  artifacts:   # Bloc obligatoire
    paths:
      - public

