meshParams={'Cells': {'ClosedWakeAbscissaCtrl': 0.5,
           'ClosedWakeAbscissaRatio': 0.25,
           'Farfield': 5.0,
           'FarfieldAspectRatio': 0.05,
           'LEFarfieldAspectRatio': 1.0,
           'LeadingEdge': 0.0005,
           'TrailingEdge': 0.005,
           'WakeFarfieldAspectRatio': 0.002},
 'Points': {'Bottom': [{'BreakPoint(x)': None,
                        'JoinCellLength': None,
                        'NPts': 150}],
            'BoundaryLayerGrowthRate': 1.05,
            'BoundaryLayerMaxPoints': 400,
            'Extrusion': 500,
            'Top': [{'BreakPoint(x)': None,
                     'JoinCellLength': None,
                     'NPts': 200}],
            'Wake': 300,
            'WakeHeightMaxPoints': 50},
 'References': {'Chord': 1.0005304259318362,
                'DeltaYPlus': 0.5,
                'Depth': 1.0,
                'Reynolds': 1333333.3333333335,
                'TorqueOrigin': [0.249602180551123, 0, 0]},
 'Sizes': {'BoundaryLayerMaxHeight': 1.0,
           'Height': 100.0,
           'TrailingEdgeTension': 0.5,
           'Wake': 100.0},
 'options': {'AirfoilFamilyName': 'AIRFOIL',
             'DenseSamplingNPts': 5000,
             'FarfieldFamilyName': 'FARFIELD',
             'LEsearchAbscissas': [0.35, 0.65],
             'LEsearchEpsilon': 1e-08,
             'MappingLaw': 'cubic',
             'NProc': 28,
             'TEclosureTolerance': 3e-05}}