#    Copyright 2023 ONERA - contact luis.bernardos@onera.fr
#
#    This file is part of MOLA.
#
#    MOLA is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    MOLA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with MOLA.  If not, see <http://www.gnu.org/licenses/>.

import numpy as np
from mola.logging import mola_logger, MolaAssertionError
from mola.cfd.preprocess.mesh import tools as mesh_tools
from mola.workflow import WorkflowManager

class WorkflowTurbomachineryManager(WorkflowManager):

    def add_isospeed_line(self, throttles, ShaftRotationSpeed=None, ParallelMode=False, initialize_from_previous=True):
        '''
        Add N operating points to compute on a same iso-speed line, where N is the size of **throttles**.
        The outflow boundary conditions is automatically detected with its `Type` starting by `Outflow`.

        .. warning::
            Cuurently, this method is designed to work with only one outflow boundary.

        Parameters
        ----------
        throttles : list or numpy.ndarray
            Values to modify to determine operating points to compute. 
            Depending on the outflow boundary condition, it could be the value of 
            `Pressure`, `MassFlow` or `valve_relax` for instance.
        ShaftRotationSpeed : float, optional
            Value of rotation speed for the iso-speed line, in rad/s.
            If not given, it is taken from Workflow attribute `ApplicationContext`.
        ParallelMode : bool, optional
            If True, all operating points are computed in parallel.
            If False, operating points on a same iso-speed line are computed sequentially.
            By default False.
        initialize_from_previous : bool, optional
            If True, each operating point on an iso-speed line is initialized by the previous point.
            The first operating point is initialized according the Workflow attribute `Initialization`.
            By default True.

        Example
        -------

        .. code-block:: python

            from mola.workflow.rotating_component import turbomachinery 

            workflow = turbomachinery.Workflow(...)
            manager = turbomachinery.WorkflowManager(workflow, '/the/path/to/my/parametric/study/')

            # Lines specific to this manager
            manager.add_isospeed_line([1e5, 1.1e5, 1.2e5])
            manager.add_isospeed_line([1e5, 1.1e5, 1.2e5], ShaftRotationSpeed=5000.) # new isospeed line for another rotation speed
            
            manager.prepare()  # at the end of this command, all the directories are deployed and job files are ready to be submitted
            manager.submit()  # submit all the jobs generated by the previous line
        '''
        if ShaftRotationSpeed is None:
            ShaftRotationSpeed = self.base_workflow.ApplicationContext.get('ShaftRotationSpeed')

        job_name = self.base_workflow.RunManagement.get('JobName', 'isospeed')

        if ParallelMode and initialize_from_previous:
            mola_logger.warning('Because ParallelMode=True, initialize_from_previous is set to False.')
            initialize_from_previous = False

        outflow_family, throttle_key = self._get_family_and_throttle_key()

        if not ParallelMode:
            self.new_job(f'isospeed_{30/np.pi*ShaftRotationSpeed:.0f}rpm')

        for throttle in throttles:
            if ParallelMode:
                self.new_job(f'{throttle_key}_{throttle:.2f}')
            self.add_variations(
                [
                    ('RunManagement|JobName', f'{job_name}_{throttle:.2f}'),
                    ('RunManagement|RunDirectory', f'{throttle_key}_{throttle:.2f}'),
                    ('ApplicationContext|ShaftRotationSpeed', ShaftRotationSpeed),
                    (f'BoundaryConditions|Family={outflow_family}|{throttle_key}', throttle),
                ], 
                initialize_from_previous = initialize_from_previous
                )
        
    def _get_family_and_throttle_key(self):
        outflow_bc = mesh_tools.get_bc_from_bc_type(self.base_workflow, 'Outflow*')
        THROTTLE_KEY = dict(
            OutflowPressure = 'Pressure', 
            OutflowMassFlow = 'MassFlow',
        )
        self._update_throttle_key_for_elsa_and_sonics(THROTTLE_KEY, outflow_bc)
        outflow_family = outflow_bc["Family"]
        throttle_key = THROTTLE_KEY[outflow_bc["Type"]]
        return outflow_family, throttle_key
    
    @staticmethod
    def _update_throttle_key_for_elsa_and_sonics(THROTTLE_KEY, outflow_bc):
        # The following lines are specific to elsA and Sonics
        outflow_bc.setdefault('valve_type', 0)
        if outflow_bc['valve_type'] == 0:
            if 'prespiv' in outflow_bc: 
                THROTTLE_KEY['OutflowRadialEquilibrium'] = 'prespiv'
            elif 'valve_ref_pres' in outflow_bc: 
                THROTTLE_KEY['OutflowRadialEquilibrium'] = 'valve_ref_pres'
        elif outflow_bc['valve_type'] in [1, 5]:
            THROTTLE_KEY['OutflowRadialEquilibrium'] = 'valve_ref_pres' 
        elif outflow_bc['valve_type'] == 2:
            THROTTLE_KEY['OutflowRadialEquilibrium'] = 'valve_ref_mflow'
        elif outflow_bc['valve_type'] in [3, 4]:
            THROTTLE_KEY['OutflowRadialEquilibrium'] = 'valve_relax' 
    