#    Copyright 2023 ONERA - contact luis.bernardos@onera.fr
#
#    This file is part of MOLA.
#
#    MOLA is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    MOLA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with MOLA.  If not, see <http://www.gnu.org/licenses/>.

import numpy as np
from mola.logging import mola_logger, MolaAssertionError
from mola.cfd.preprocess.mesh import tools as mesh_tools
from mola.workflow import WorkflowManager

class WorkflowTurbomachineryManager(WorkflowManager):
    '''
    Example
    -------

    .. code-block:: python

        from mola.workflow.rotating_component import turbomachinery 

        workflow = turbomachinery.Workflow(...)
        manager = turbomachinery.WorkflowManager(workflow, '/the/path/to/my/parametric/study/')

        # Lines specific to this manager
        manager.add_isospeed_line([1e5, 1.1e5, 1.2e5])
        manager.add_isospeed_line([1e5, 1.1e5, 1.2e5], ShaftRotationSpeed=5000.) # new isospeed line for another rotation speed
        
        manager.prepare()  # at the end of this command, all the directories are deployed and job files are ready to be submitted
        manager.submit()  # submit all the jobs generated by the previous line

    '''

    def add_isospeed_line(self, throttles, ShaftRotationSpeed=None, ParallelMode=False, initialize_from_previous=True):
        if ShaftRotationSpeed is None:
            ShaftRotationSpeed = self.base_workflow.ApplicationContext.get('ShaftRotationSpeed')

        job_name = self.base_workflow.RunManagement.get('JobName', 'isospeed')

        if ParallelMode and initialize_from_previous:
            mola_logger.warning('Because ParallelMode=True, initialize_from_previous is set to False.')
            initialize_from_previous = False

        outflow_bc = mesh_tools.get_bc_from_bc_type(self.base_workflow, 'Outflow*')

        THROTTLE_KEY = dict(
            OutflowPressure = 'Pressure', 
            OutflowMassFlow = 'MassFlow',
        )
        # # The following lines are specific to elsA
        # if outflow_bc['valve_type'] == 0:
        #     if 'prespiv' in outflow_bc: 
        #         THROTTLE_KEY['OutflowRadialEquilibrium'] = 'prespiv'
        #     elif 'valve_ref_pres' in outflow_bc: 
        #         THROTTLE_KEY['OutflowRadialEquilibrium'] = 'valve_ref_pres'
        # elif outflow_bc['valve_type'] in [1, 5]:
        #     THROTTLE_KEY['OutflowRadialEquilibrium'] = 'valve_ref_pres' 
        # elif outflow_bc['valve_type'] == 2:
        #     THROTTLE_KEY['OutflowRadialEquilibrium'] = 'valve_ref_mflow'
        # elif outflow_bc['valve_type'] in [3, 4]:
        #     THROTTLE_KEY['OutflowRadialEquilibrium'] = 'valve_relax' 

        throttle_key = THROTTLE_KEY[outflow_bc["Type"]]

        if not ParallelMode:
            self.new_job(f'isospeed_{30/np.pi*ShaftRotationSpeed:.0f}rpm')

        for throttle in throttles:
            if ParallelMode:
                self.new_job(f'{throttle_key}_{throttle:.2f}')
            self.add_variations(
                [
                    ('RunManagement|JobName', f'{job_name}_{throttle:.2f}'),
                    ('RunManagement|RunDirectory', f'{throttle_key}_{throttle:.2f}'),
                    ('ApplicationContext|ShaftRotationSpeed', ShaftRotationSpeed),
                    (f'BoundaryConditions|Family={outflow_bc["Family"]}|{throttle_key}', throttle),
                ], 
                initialize_from_previous = initialize_from_previous
                )
        