#    Copyright 2023 ONERA - contact luis.bernardos@onera.fr
#
#    This file is part of MOLA.
#
#    MOLA is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    MOLA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with MOLA.  If not, see <http://www.gnu.org/licenses/>.

import os
from typing import List
import copy
from fnmatch import fnmatch

from mola.workflow import Workflow
from mola import __MOLA_PATH__
import mola.naming_conventions as names
from mola.logging import mola_logger, MolaAssertionError, MolaException, CYAN, ENDC
from mola.cfd.preprocess.run_manager import run_manager
from mola.cfd.preprocess.write_cfd_files import write_cfd_files
from mola import server as SV

class WorkflowManager():
    '''
    This class allows to submit in sequential or parallel mode, maybe on a remote machine, 
    a bunch of workflows by applying variations from a base workflow.
    It is particularly useful to perform parametric studies.

    Parameters
    ----------

    workflow : :py:class:`Workflow` object
        Base workflow, used to generate variations around it. See the docummentation 
        of :py:class:`WorkflowDispatcher` object for details.

    root_directory : str
        Target root directory from which the multiple workflows will be deployed.

    data_directory : str, optional
        Directory where the data files common to the workflows will be placed
        (refer to the documentation of :py:class:`WorkflowSender` for more information).
        It is relative to **root_directory**.

        By default it is set to ``'SHARED_DATA'``, so shared data files will be in 
        ``<root_directory>/SHARED_DATA/``.

    skip_if_exists: bool, optional
        If True, it will simply pass over directories that were already created in a 
        previous usage of ``WorkflowManager``. 
        
        .. hint:: It is useful to add new operating points to a parametric study previously submitted.
        
        If False, an error is raise is a directory already exists.

        Default value is False.

    Example
    -------

    .. code-block:: python

        from mola.workflow import Workflow
        from mola.workflow import manager as WM 

        workflow = Workflow(...)
        manager = WM.WorkflowManager(workflow, '/the/path/to/my/parametric/study/')

        for BCWall in ['WallViscous', 'WallInviscid']:
            manager.new_job(BCWall)  # There will be two job submitted, one for 'WallViscous' and one for 'WallInviscid'
            for velocity in [50., 20., 80.]:
                manager.add_variations(
                    [
                        ('RunManagement|JobName', BCWall),
                        ('RunManagement|RunDirectory', f'Velocity_{velocity}'),
                        ('Flow|Velocity', velocity),
                        ('BoundaryConditions|Family=Wall|Type', BCWall),
                    ], 
                )
        
        manager.prepare()  # at the end of this command, all the directories are deployed and job files are ready to be submitted
        manager.submit()  # submit all the jobs '{names.FILE_JOB_SEQUENCE}' generated by the previous line

    ``add_variations`` takes a list of parameters to make vary compared to the base workflow.
    Each variation is a tuple of two elements:

    #. a path (:py:class:`str`) to the parameter to make vary in the base workflow. 
       The separator is a pipe '|'. In the example given above:

       * ``'RunManagement|JobName'`` selects ``workflow.RunManagement['JobName']``.

       * ``'BoundaryConditions|Family=Wall|Type'`` selects ``workflow.BoundaryConditions[<index>]['Type']``.
         Because ``workflow.BoundaryConditions`` is a :py:class:`list`, ``Family=Wall`` is a mean to select 
         the boundary condition `BC` in this list (remember `BC` is a :py:class:`dict`) such as ``BC['Family']=='Wall'``. 
         ``workflow.BoundaryConditions[<index>]`` is that ``BC``, and finally the value corresponding to the key 
         ``'Type'`` is selected.

    #. the new value to apply to this selected parameter.

    '''

    def __init__(self, 
                 workflow, 
                 root_directory='.', 
                 data_directory='SHARED_DATA', 
                 skip_if_exists=True,
                 ):

        # table_of_workflows = [[A1, B1, ...], [A2, B2, ...], ...]
        #   several jobs in parallel: 
        #     sequence of [A1, B1, ...]
        #     sequence of [A2, B2, ...]
        #     ...
        #
        # Warning: if A1 == A2 (same Python object, without copy), then it will bug without raising an error

        self.root_directory = root_directory
        self.data_directory = data_directory
        self.skip_if_exists = skip_if_exists
        self.machine = None
        self.base_workflow = workflow
        self.dispatcher = WorkflowDispatcher(workflow)

    def new_job(self, directory):
        self.dispatcher.new_job(directory)
    
    def add_variations(self, variations, initialize_from_previous=True):
        self.dispatcher.add_variations(variations, initialize_from_previous)

    def prepare(self):
        self._init_table_of_workflows()
        SV.makedirs_remote(self.root_directory, machine=self.machine)
        for sequence_of_workflows in self.table_of_workflows:
            sequence_of_workflows.prepare()

    def submit(self):
        for sequence_of_workflows in self.table_of_workflows:
            sequence_of_workflows.submit()

    def _init_table_of_workflows(self):
        self.table_of_workflows = []
        for i, sequence in enumerate(self.dispatcher.table_of_workflows):
            root_absolute_directory = os.path.join(self.root_directory, self.dispatcher.root_directories[i])
            data_absolute_directory = os.path.join(self.root_directory, self.data_directory)

            sequential_scheduler = WorkflowSequentialManager(
                sequence, 
                root_directory=root_absolute_directory, 
                data_directory=data_absolute_directory, 
                skip_if_exists=self.skip_if_exists
                )
            self.table_of_workflows.append(sequential_scheduler)

        self.machine = sequential_scheduler.machine
    
    def gather_signals(self, queries, filename=None):
        """
        get scalars from signals.cgns and plot a curve
        plot several curves (one per case) on the same plot
        get a surface from each instant
        """
        if not filename:
            filename = os.path.join(names.DIRECTORY_OUTPUT, names.FILE_OUTPUT_1D)

        def _extract(w, queries):
            path = ...
            signals = cgns.load(os.path.join(path, filename))
            ...
            return data

        all_data = []
        for case in self.all_cases:
            # read the workflow
            w = read_workflow(case)
            status = w.simulation_status()
            if status == names.FILE_JOB_COMPLETED:
                data = _extract(w, queries)
                add_to_all_data(data)
        
        return all_data


class WorkflowDispatcher():
    '''
    This class allows creating "variations" from a base workflow. 
    It may be used to prepare a parametric study on one or several parameters.

    To create a WorkflowDispatcher object, just give a base workflow:
     
    .. code-block:: python

        from mola.workflow import Workflow
        from mola.workflow import manager as WM 

        workflow = Workflow(...)
        dispatcher = WM.WorkflowDispatcher(workflow)

    Once instanciated, the user may use the method ``new_job`` and 
    ``add_variations`` to generate workflows derivated from the base workflow.
    (see the example below).

    .. hint::

        This class is intended to work with :py:class:`WorkflowManager`,
        in order to submit the workflows generated by :py:class:`WorkflowDispatcher`.

    '''

    def __init__(self, workflow):
        self.base_workflow = workflow
        self.table_of_workflows = []
        self.workflows_in_current_job = None
        self.root_directories = []

    def new_job(self, directory):
        self.workflows_in_current_job = []
        self.table_of_workflows.append(self.workflows_in_current_job)
        self.root_directories.append(directory)
    
    def add_variations(self, variations, initialize_from_previous=True):
        self._check_new_job_is_declared()
        new_workflow = copy.deepcopy(self.base_workflow)

        if initialize_from_previous and len(self.workflows_in_current_job) > 0:
            self._add_variations_to_initialize_from_previous(variations)

        for request, value in variations:
            path_in_workflow = self.request_to_paths(request)
            set_value_on_leaf(new_workflow, path_in_workflow, value)

        self.workflows_in_current_job.append(new_workflow)

    # def reorder(self, request, reverse=False):
    #     path_in_workflow = self.request_to_paths(request)
    #     leaves = [get_value_on_leaf(workflow, path_in_workflow) for workflow in self.workflows]
    #     # Sort workflows accordind leaves
    #     self.workflows = [w for _, w in sorted(zip(leaves, self.workflows))]
    #     if reverse:
    #         self.workflows = self.workflows[::-1]
    
    def _check_new_job_is_declared(self):
        if self.workflows_in_current_job is None:
            raise MolaAssertionError('Before calling `add_variations`, `new_job` must be called first to declare directory.')
    
    def _add_variations_to_initialize_from_previous(self, variations):
        try:
            previous_workflow = self.workflows_in_current_job[-1]
            previous_case_path = previous_workflow.RunManagement['RunDirectory']
            init_variations = [
                ('Initialization|method', 'copy'),
                ('Initialization|source', f'../{previous_case_path}/{names.FILE_INPUT_SOLVER}'),
            ]
            variations += init_variations
        except IndexError:
            mola_logger.warning(f'Cannot initialize the first case of a sequence ({self.root_directories[-1]}) from a previous case')

    @staticmethod
    def request_to_paths(request):
        if isinstance(request, str):
            request = request.split('|')
        return request

    def get_directories_in_current_job(self, worflows_sequence=None):
        if worflows_sequence is None:
            worflows_sequence = self.workflows_in_current_job
        return [workflow.RunManagement['RunDirectory'] for workflow in worflows_sequence]

    def get_local_directories(self):
        directories = []
        for worflows_sequence in self.table_of_workflows:
            job_directories = self.get_directories_in_current_job(worflows_sequence)
            directories.append(job_directories)
        return directories

    def get_directories(self):
        directories = []
        for root, worflows_sequence in zip(self.root_directories, self.table_of_workflows):
            job_directories = self.get_directories_in_current_job(worflows_sequence)
            directories.extend([os.path.join(root, d) for d in job_directories])
        return directories


class WorkflowSequentialManager():
    '''
    This class is instanciated by :py:meth:`WorkflowManager._init_table_of_workflows`.
    It is **not intented to be called directly by user**.

    It handles the creation of one "sequence" of cases (generated from **workflows**), 
    run sequentially with the job file :mola_name:`FILE_JOB_SEQUENCE`.
    '''

    _sequential_job_filename = names.FILE_JOB_SEQUENCE

    def __init__(self, workflows: List[Workflow], root_directory, data_directory, skip_if_exists=False):

        self.workflows = workflows
        self.root_directory = root_directory
        self.data_directory = data_directory
        self.skip_if_exists = skip_if_exists

        self._check_structure_of_workflows()
        self._check_and_set_local_paths()
        self._check_all_workflows_have_different_working_directories()
        self._set_machine()

    def _check_structure_of_workflows(self):
        assert isinstance(self.workflows, list)
        for workflow in self.workflows:
            assert isinstance(workflow, Workflow)

    def _check_all_workflows_have_different_working_directories(self):
        assert len(set(self.cases_local_paths)) == len(self.workflows), 'Several workflows have the same working directory'

    def _check_and_set_local_paths(self):
        self.cases_local_paths = []
        for workflow in self.workflows:
            path = workflow.RunManagement['RunDirectory']
            if not path.startswith(os.path.sep):
                # local path
                self.cases_local_paths.append(path)
                workflow.RunManagement['RunDirectory'] = os.path.join(self.root_directory, path)
            else:
                # absolute path
                if not path.startswith(self.root_directory):
                    raise MolaAssertionError(
                        f'RunDirectory {path} is not consistent with the root path {self.root_directory}.'
                        )
                self.cases_local_paths.append(path.replace(self.root_directory, ''))

    def _set_machine(self):
        first_workflow = self.workflows[0] 
        RunManagement = copy.deepcopy(first_workflow.RunManagement)
        scheduler_options = run_manager.set_default(RunManagement)
        self.machine = RunManagement['Machine']
        self.manager = RunManagement['Scheduler']
        self.job_text = write_cfd_files.get_job_text(first_workflow.Solver, RunManagement, scheduler_options)

    def prepare(self):
        SV.makedirs_remote(self.root_directory, machine=self.machine)
        for workflow in self.workflows:
            mola_logger.info(f"\n{CYAN}  > preparing {workflow.RunManagement['RunDirectory']}...{ENDC}")
            if self.skip_if_exists and SV.is_directory(workflow.RunManagement['RunDirectory'], self.machine):
                mola_logger.warning(f"Skip directory {workflow.RunManagement['RunDirectory']} that already exists")
                continue
            workflow.write_tree_remote(data_directory=self.data_directory)

        self.write_sequence_job()

    def write_sequence_job(self):
        paths_in_bash = '"{}"'.format(' '.join(self.cases_local_paths))
        loop_on_cases = self._build_loop_on_cases(paths_in_bash, self._sequential_job_filename)
        SV.save_file_maybe_remote(self._sequential_job_filename, self.job_text + loop_on_cases, self.root_directory, machine=self.machine)

    def submit(self):
        mola_logger.info(f'  > submission of job sequence in {self.root_directory}')
        if self.manager == 'SLURM':
            command = f"cd {self.root_directory}; sbatch {self._sequential_job_filename}"
        else:
            command = f"cd {self.root_directory}; ./{self._sequential_job_filename}"

        SV.submit_command(command, self.machine)

    @staticmethod
    def _build_loop_on_cases(sequence_of_paths, sequential_job_filename):

        loop_on_cases = f'''
SECONDS=0
SEQUENCE_OF_PATHS={sequence_of_paths}

for case in $SEQUENCE_OF_PATHS; do

    echo "entering $case"
    cd $case

    while [ ! -f "{names.FILE_JOB_COMPLETED}" ] && [ ! -f "{names.FILE_JOB_FAILED}" ]; do

        mola_prepare {names.FILE_INPUT_WORKLFOW}

        echo "compute case $case at $SECONDS s"
        ./{names.FILE_JOB}

        if [ -f "{names.FILE_NEWJOB_REQUIRED}" ]; then
            rm {names.FILE_NEWJOB_REQUIRED}
            echo "LAUNCHING THIS JOB AGAIN"
            cd ..
            sbatch {sequential_job_filename} --dependency=singleton
            exit 0
        elif [ -f "{names.FILE_ERROR_PREPARING_WORKFLOW}" ]; then
            exit 0
        fi
    done

    cd ..

done
'''
        return loop_on_cases


class WorkflowSender():
    '''
    This class allow to save in a file :mola_name:`FILE_INPUT_WORKLFOW` 
    the parametrization of a workflow that has been just instanciated, 
    without calling its method ``prepare``, 
    and to send this file to ``workflow.RunManagement['RunDirectory']``, 
    eventually on a remote machine designated by ``workflow.RunManagement['RunDirectory']``.

    Notice than the workflow may have paths to files in its parameters, 
    for instance ``workflow.RawMeshComponents[<one_component>]['Source'] = 'mesh.cgns'``.
    In that case, these files are also copied to a distant repository given by **data_directory**. 
    If not given, the same directory ``self.workflow.RunManagement['RunDirectory']`` will be taken.
    By default, files that are copied are found following the pattern ``*.cgns``.

    Paths in the workflow parameters are then automatically updated to be consistent with
    the new localization of theses files.

    .. info:: 

        The most direct application of this class is its wrapping in the method ``write_tree_remote`` of
        the class :py:class:``Workflow``. 

    .. info:: 

        If you need to change the patterns used to found files to copy;
        the argument ``patterns_to_copy_files`` may be pass to :py:meth:`WorkflowSender.__init__`
        Remember that by default, ``patterns_to_copy_files=['*.cgns']``.

    Example
    -------

    .. code-block::python

        from mola.workflow import Workflow
        from mola.workflow import manager as WM 

        workflow = Workflow(...)
        sender = WM.WorkflowSender(workflow, data_directory=data_directory)
        sender.apply()

    '''

    _workflow_filename = names.FILE_INPUT_WORKLFOW

    def __init__(self, workflow, data_directory=None, patterns_to_copy_files=None):
        self.workflow = copy.deepcopy(workflow)
        self.run_directory = copy.deepcopy(self.workflow.RunManagement['RunDirectory'])

        if data_directory is None:
            self.data_directory = self.run_directory
        else:
            self.data_directory = data_directory

        if patterns_to_copy_files is None:
            self.patterns_to_copy_files = ['*.cgns']
        else:
            self.patterns_to_copy_files = patterns_to_copy_files
        
        run_manager.set_default_machine(self.workflow.RunManagement)
        self.machine = self.workflow.RunManagement['Machine']
        
    def apply(self):
        
        destination = os.path.join(self.run_directory, self._workflow_filename)
        self.workflow.RunManagement['RunDirectory'] = '.'
        
        run_on_localhost = SV.run_on_localhost(self.machine, self.run_directory)
        if run_on_localhost:    
            self.workflow.set_workflow_parameters_in_tree()    
            SV.makedirs_remote(self.run_directory, machine='localhost')    
            self.workflow.write_tree(filename=destination)
            
        else:
            self._copy_files_and_update_paths_in_workflow()

            self.workflow.set_workflow_parameters_in_tree()
            self.workflow.write_tree(filename=self._workflow_filename)
            SV.copy_remote(
                source_path=self._workflow_filename, 
                destination_path=destination, 
                destination_machine=self.machine,
                )
            SV.remove_path(self._workflow_filename, machine='localhost')

    def _copy_files_and_update_paths_in_workflow(self):
        files2copy = find_matching_leaves(
            self.workflow, 
            self.patterns_to_copy_files, 
            operation=self._get_adapted_path,
            excluded_attributes=['Extractions']
            )
        
        files2copy = [filename for filename in files2copy if not filename.endswith(names.FILE_INPUT_SOLVER)]
        
        for filename in files2copy:
            self._copy_file_to_data_directory(filename)
        
    def _copy_file_to_data_directory(self, path):
        machine = self.machine
        filename = path.split(os.path.sep)[-1]
        new_filename = os.path.join(self.data_directory, filename)

        if not SV.is_existing_path(new_filename, machine=machine):
            mola_logger.info(f'copy {path} to {self.data_directory}')
            SV.makedirs_remote(self.data_directory, machine=machine)
            SV.copy_remote(
                source_path=path,
                destination_path=new_filename,
                destination_machine=machine
            )
    
    def _get_adapted_path(self, path):
        filename = path.split(os.path.sep)[-1]
        dir_path = os.path.relpath(self.data_directory, start=self.run_directory)
        return os.path.join(dir_path, filename)
    

def set_value_on_leaf(tree, path: str, value)-> None:
    '''
    Set a new value for the leaf in Workflow parameters selected 
    by its path.

    Parameters
    ----------
    tree : Workflow or dict or list
        Workflow or a sub-tree of Workflow parameters.
    path : str
        Path of the leaf to modify in tree, using the pipe '|' as separator.
        Examples: 
        * `'RunManagement|JobName'`
        * `'BoundaryConditions|Family=Wall|Type'``

    value : 
        the new value to set for the selected leaf.

    '''
    current_path = path[0]

    if isinstance(tree, Workflow):
        if len(path) == 1:
            setattr(tree, current_path, value)
        else:
            attr = getattr(tree, current_path)
            set_value_on_leaf(attr, path[1:], value)

    elif isinstance(tree, dict):
        if len(path) == 1:
            tree[current_path] = value
        else:
            set_value_on_leaf(tree[current_path], path[1:], value)
    
    elif isinstance(tree, (list, tuple)):
        if not len(path) > 1:
            raise MolaAssertionError(
                f'Path cannot end with a list (current path is {path}). '
                'You must add the key of the selected dictionary to set.'
                )
        assert current_path.count('=') == 1
        # search the good element 
        name, search_value = current_path.split('=')
        found = False
        for dico in tree:
            if name in dico and str(dico[name]) == search_value:
                found = True
                break
        assert found
        set_value_on_leaf(dico, path[1:], value)
    
    else:
        raise MolaException(f'Unknown type: {type(tree)}')
          
def get_value_on_leaf(tree, path: str):
    # for now, it used only in tests
    try:
        current_path = path[0]
    except IndexError:
        return tree
    
    if isinstance(tree, Workflow):
        return get_value_on_leaf(getattr(tree, current_path), path[1:])

    elif isinstance(tree, dict):
        return get_value_on_leaf(tree[current_path], path[1:])
    
    elif isinstance(tree, (list, tuple)):
        assert current_path.count('=') == 1
        # search the good element 
        name, search_value = current_path.split('=')
        found = False
        for dico in tree:
            if name in dico and str(dico[name]) == search_value:
                found = True
                break
        assert found
        return get_value_on_leaf(dico, path[1:])
    
    else:
        raise MolaException(f'Unknown type: {type(tree)}')

def find_matching_leaves(tree, patterns: list, operation=None, excluded_attributes=[]) -> list:
    '''
    Find leaves in Workflow parameters matching one of the given patterns, 
    optionaly apply (in-place) an operation on them,
    and return the list of values of matching leaves.

    Parameters
    ----------
    tree : Workflow or dict or list
        Workflow or a sub-tree of Workflow parameters.

    patterns : :py:class:`list` of :py:class:`str`
        patterns used to find leaves in **tree**. 
        For example, to select CGNS files used by the Workflow:

        >>> patterns = ['*.cgns']

    operation : function, optional
        If not None, this function is applied to all matching leaves.
        For example, to add the preffix to strings matching **patterns**:

        >>> operation = ['*.cgns']
    
    excluded_attributes : :py:class:`list` of :py:class:`str`
        Names of attributes of Workflow to exclude of the search.

    Returns
    -------
    list
        values of leaves matching patterns.
    '''
    matches = []

    if isinstance(tree, Workflow):
        for attr_name, attr_value in tree.__dict__.items():
            if attr_name.startswith('_') or attr_name in excluded_attributes:
                continue
            matches.extend(find_matching_leaves(attr_value, patterns, operation))

    elif isinstance(tree, dict):
        for key, value in tree.items():
            if isinstance(value, list):
                for item in value:
                    matches.extend(find_matching_leaves(item, patterns, operation))
            elif isinstance(value, dict):
                matches.extend(find_matching_leaves(value, patterns, operation))
            else:
                for pattern in patterns:
                    if fnmatch(str(value), pattern):
                        matches.append(value)
                        if operation:
                            tree[key] = operation(value)

    elif isinstance(tree, list):
        for item in tree:
            matches.extend(find_matching_leaves(item, patterns, operation))

    return matches


