#    Copyright 2023 ONERA - contact luis.bernardos@onera.fr
#
#    This file is part of MOLA.
#
#    MOLA is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    MOLA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with MOLA.  If not, see <http://www.gnu.org/licenses/>.

import os
from typing import List
import copy
from fnmatch import fnmatch

from mola import __MOLA_PATH__
from mola.logging import mola_logger, MolaAssertionError, MolaException, CYAN, ENDC
from mola.workflow import Workflow
from mola.cfd.preprocess.write_cfd_files import write_cfd_files
from mola import server as SV


class WorkflowDispatcher():
    '''
    This class allows creating "variations" from a base workflow. 
    It may be used to prepare a parametric study on one or several parameters.

    To create a WorkflowDispatcher object, just give a base workflow:
     
    .. code-block:: python

        from mola.workflow import Workflow
        from mola.workflow import workflow_manager as WM 

        workflow = Workflow(...)
        dispatcher = WM.WorkflowDispatcher(workflow)

    Once instanciated, the user may use the method ``new_job`` and 
    ``add_variations`` to generate workflows derivated from the base workflow.
    (see the example below).

    .. hint::

        This class is intended to work with :py:class:``WorkflowParallelScheduler``,
        in order to submit the workflows generated by :py:class:``WorkflowDispatcher``.

    Example
    -------

    .. code-block:: python

        from mola.workflow import Workflow
        from mola.workflow import workflow_manager as WM 

        workflow = Workflow(...)
        dispatcher = WM.WorkflowDispatcher(workflow)

        for BCWall in ['WallViscous', 'WallInviscid']:
            dispatcher.new_job(BCWall)  # There will be two job submitted, one for 'WallViscous' and one for 'WallInviscid'
            for velocity in [50., 20., 80.]:
                dispatcher.add_variations(
                    [
                        ('RunManagement|JobName', BCWall),
                        ('RunManagement|RunDirectory', f'Velocity_{velocity}'),
                        ('Flow|Velocity', velocity),
                        ('BoundaryConditions|Family=Wall|type', BCWall),
                    ], 
                )

    ``add_variations`` takes a list of parameters to make vary compared to the base workflow.
    Each variation is a tuple of two elements:

    #. a path (:py:class:`str`) to the parameter to make vary in the base workflow. 
       The separator is a pipe '|'. In the example given above:

       * ``'RunManagement|JobName'`` selects ``workflow.RunManagement['JobName']``.

       * ``'BoundaryConditions|Family=Wall|type'`` selects ``workflow.BoundaryConditions[<index>]['type']``.
         Because ``workflow.BoundaryConditions`` is a :py:class:`list`, ``Family=Wall`` is a mean to select 
         the boundary condition `BC` in this list (remember `BC` is a :py:class:`dict`) such as ``BC['Family']=='Wall'``. 
         ``workflow.BoundaryConditions[<index>]`` is that ``BC``, and finally the value corresponding to the key 
         ``'type'`` is selected.

    #. the new value to apply to this selected parameter.

    '''

    def __init__(self, workflow):
        self.base_workflow = workflow
        self.table_of_workflows = []
        self.workflows_in_current_job = None
        self.root_directories = []

    def new_job(self, directory):
        self.workflows_in_current_job = []
        self.table_of_workflows.append(self.workflows_in_current_job)
        self.root_directories.append(directory)
    
    def add_variations(self, variations, initialize_from_previous=True):
        self._check_new_job_is_declared()
        new_workflow = copy.deepcopy(self.base_workflow)

        if initialize_from_previous and len(self.workflows_in_current_job) > 0:
            self._add_variations_to_initialize_from_previous(variations)

        for request, value in variations:
            path_in_workflow = self.request_to_paths(request)
            set_value_on_leaf(new_workflow, path_in_workflow, value)

        self.workflows_in_current_job.append(new_workflow)

    # def reorder(self, request, reverse=False):
    #     path_in_workflow = self.request_to_paths(request)
    #     leaves = [get_value_on_leaf(workflow, path_in_workflow) for workflow in self.workflows]
    #     # Sort workflows accordind leaves
    #     self.workflows = [w for _, w in sorted(zip(leaves, self.workflows))]
    #     if reverse:
    #         self.workflows = self.workflows[::-1]
    
    def _check_new_job_is_declared(self):
        if self.workflows_in_current_job is None:
            raise MolaAssertionError('Before calling `add_variations`, `new_job` must be called first to declare directory.')
    
    def _add_variations_to_initialize_from_previous(self, variations):
        try:
            previous_workflow = self.workflows_in_current_job[-1]
            previous_case_path = previous_workflow.RunManagement['RunDirectory']
            init_variations = [
                ('Initialization|method', 'copy'),
                ('Initialization|source', f'../{previous_case_path}/OUTPUT/fields.cgns'),
            ]
            variations += init_variations
        except IndexError:
            mola_logger.warning(f'Cannot initialize the first case of a sequence ({self.root_directories[-1]}) from a previous case')

    @staticmethod
    def request_to_paths(request):
        if isinstance(request, str):
            request = request.split('|')
        return request

    def get_directories_in_current_job(self, worflows_sequence=None):
        if worflows_sequence is None:
            worflows_sequence = self.workflows_in_current_job
        return [workflow.RunManagement['RunDirectory'] for workflow in worflows_sequence]

    def get_local_directories(self):
        directories = []
        for worflows_sequence in self.table_of_workflows:
            job_directories = self.get_directories_in_current_job(worflows_sequence)
            directories.append(job_directories)
        return directories

    def get_directories(self):
        directories = []
        for root, worflows_sequence in zip(self.root_directories, self.table_of_workflows):
            job_directories = self.get_directories_in_current_job(worflows_sequence)
            directories.extend([os.path.join(root, d) for d in job_directories])
        return directories


class WorkflowParallelScheduler():
    '''
    This class allows to submit in sequential or parallel mode, maybe on a remote machine, 
    a bunch of workflows previously generated with :py:class:`WorkflowDispatcher`.
    It is particularly useful to perform parametric studies.

    Parameters
    ----------

    dispatcher : :py:class:`WorkflowDispatcher` object
        Previously generated :py:class:`WorkflowDispatcher` object (refer to the dedicated documentation).

    root_directory : str
        Target root directory from which the multiple workflows will be deployed.

    data_directory : str, optional
        Directory where the data files common to the workflows will be placed
        (refer to the documentation of :py:class:`WorkflowSender` for more information).
        It is relative to **root_directory**.

        By default it is set to ``'SHARED_DATA'``, so shared data files will be in 
        ``<root_directory>/SHARED_DATA/``.

    skip_if_exists: bool, optional
        If True, it will simply pass over directories that were already created in a 
        previous usage of ``WorkflowParallelScheduler``. 
        
        .. hint:: It is useful to add new operating points to a parametric study previously submitted.
        
        If False, an error is raise is a directory already exists.

        Default value is False.

    Example
    -------

    See documentation of :py:class:`WorkflowDispatcher` to create the dispatcher object, and then do:

    .. code-block:: python

        from mola.workflow import workflow_manager as WM 
        
        scheduler = WM.WorkflowParallelScheduler(dispatcher, '/the/path/to/my/parametric/study/')
        scheduler.prepare()  # at the end of this command, all the directories are deployed and job files are ready to be submitted
        scheduler.submit()  # submit all the jobs 'job_sequence.sh' generated by the previous line

    '''

    def __init__(self, dispatcher, root_directory='.', data_directory='SHARED_DATA', skip_if_exists=False):

        # table_of_workflows = [[A1, B1, ...], [A2, B2, ...], ...]
        #   several jobs in parallel: 
        #     sequence of [A1, B1, ...]
        #     sequence of [A2, B2, ...]
        #     ...
        #
        # Warning: if A1 == A2 (same Python object, without copy), then it will bug without raising an error

        self.skip_if_exists = skip_if_exists
        self.machine = None
        self.root_directory = root_directory
        self.data_directory = data_directory
        self.sequences_directories = dispatcher.root_directories
        self._set_table_of_workflows(dispatcher.table_of_workflows)

    def _set_table_of_workflows(self, table_of_workflows):
        assert isinstance(table_of_workflows, list)
        self.table_of_workflows = []
        for i, sequence in enumerate(table_of_workflows):
            root_absolute_directory = os.path.join(self.root_directory, self.sequences_directories[i])
            data_absolute_directory = os.path.join(self.root_directory, self.data_directory)

            sequential_scheduler = WorkflowSequentialScheduler(
                sequence, 
                root_directory=root_absolute_directory, 
                data_directory=data_absolute_directory, 
                skip_if_exists=self.skip_if_exists
                )
            self.table_of_workflows.append(sequential_scheduler)

        self.machine = sequential_scheduler.machine
        
    def prepare(self):
        SV.makedirs_remote(self.root_directory, machine=self.machine)
        for sequence_of_workflows in self.table_of_workflows:
            sequence_of_workflows.prepare()

    def submit(self):
        for sequence_of_workflows in self.table_of_workflows:
            sequence_of_workflows.submit()

    
class WorkflowSequentialScheduler():

    def __init__(self, workflows: List[Workflow], root_directory, data_directory, skip_if_exists=False):

        self.root_directory = root_directory
        self.workflows = workflows
        self._check_structure_of_workflows()
        self._check_and_set_local_paths()
        self._check_all_workflows_have_different_working_directories()
        self._set_machine()
        self._sequential_job_filename = 'job_sequence.sh'
        self.skip_if_exists = skip_if_exists
        self.data_directory = data_directory

    def _check_structure_of_workflows(self):
        assert isinstance(self.workflows, list)
        for workflow in self.workflows:
            assert isinstance(workflow, Workflow)

    def _check_all_workflows_have_different_working_directories(self):
        assert len(set(self.cases_local_paths)) == len(self.workflows), 'Several workflows have the same working directory'

    def _check_and_set_local_paths(self):
        self.cases_local_paths = []
        for workflow in self.workflows:
            path = workflow.RunManagement['RunDirectory']
            if not path.startswith(os.path.sep):
                # local path
                self.cases_local_paths.append(path)
                workflow.RunManagement['RunDirectory'] = os.path.join(self.root_directory, path)
            else:
                # absolute path
                if not path.startswith(self.root_directory):
                    raise MolaAssertionError(
                        f'RunDirectory {path} is not consistent with the root path {self.root_directory}.'
                        )
                self.cases_local_paths.append(path.replace(self.root_directory, ''))

    def _set_machine(self):
        first_workflow = self.workflows[0] 
        RunManagement = copy.deepcopy(first_workflow.RunManagement)
        write_cfd_files.set_default(RunManagement)
        self.machine = RunManagement['Machine']
        self.scheduler, _ = SV.get_scheduler_and_options(RunManagement)
        self.run_on_localhost = SV.run_on_localhost(self.machine, RunManagement['RunDirectory'])
        self.job_text = SV.get_job_text(RunManagement, first_workflow.Solver)

    def prepare(self):
        SV.makedirs_remote(self.root_directory, machine=self.machine)
        for workflow in self.workflows:
            mola_logger.info(f"\n{CYAN}  > preparing {workflow.RunManagement['RunDirectory']}...{ENDC}")
            if self.skip_if_exists and SV.is_directory(workflow.RunManagement['RunDirectory'], self.machine):
                mola_logger.warning(f"Skip directory {workflow.RunManagement['RunDirectory']} that already exists")
                continue
            workflow.write_tree_remote(data_directory=self.data_directory)

        self.write_sequence_job()
    
    # @staticmethod
    # def prepare_workflow(workflow):
    #     workflow.prepare()
    #     workflow.write_cfd_files()

    def write_sequence_job(self):
        paths_in_bash = '"{}"'.format(' '.join(self.cases_local_paths))
        loop_on_cases = build_loop_on_cases(paths_in_bash, self._sequential_job_filename)
        SV.save_file_maybe_remote(self._sequential_job_filename, self.job_text + loop_on_cases, self.root_directory, machine=self.machine)

    def submit(self):
        mola_logger.info(f'  > submission of job sequence in {self.root_directory}')
        if self.scheduler == 'SLURM':
            command = f"cd {self.root_directory}; sbatch {self._sequential_job_filename}"
        else:
            command = f"cd {self.root_directory}; ./{self._sequential_job_filename}"

        SV.submit_command(command, self.machine)


class WorkflowSender():
    '''
    This class allow to save in a file ``workflow.cgns`` 
    the parametrization of a workflow that has been just instanciated, 
    without calling its method ``prepare``, 
    and to send this file to ``workflow.RunManagement['RunDirectory']``, 
    eventually on a remote machine designated by ``workflow.RunManagement['RunDirectory']``.

    Notice than the workflow may have paths to files in its parameters, 
    for instance ``workflow.RawMeshComponents[<one_component>]['Source'] = 'mesh.cgns'``.
    In that case, this files are also copied to a distant repository given by **data_directory**. 
    If not given, the same directory ``self.workflow.RunManagement['RunDirectory']`` will be taken.

    Paths in the workflow parameters are then automatically updated to be consistent with
    the new localization of theses files.

    .. info:: 

        The most direct application of this class is its wrapping in the method ``write_tree_remote`` of
        the class :py:class:``Workflow``. 

    Example
    -------

    .. code-block::python

        from mola.workflow import Workflow
        from mola.workflow import workflow_manager as WM 

        workflow = Workflow(...)
        sender = WM.WorkflowSender(workflow, data_directory=data_directory)
        sender.apply()

    '''

    def __init__(self, workflow, data_directory=None):
        self.workflow = copy.deepcopy(workflow)
        self.run_directory = copy.deepcopy(self.workflow.RunManagement['RunDirectory'])
        if data_directory is None:
            self.data_directory = self.run_directory
        else:
            self.data_directory = data_directory
        
        write_cfd_files.set_default_machine(self.workflow.RunManagement)
        self.machine = self.workflow.RunManagement['Machine']
        self._workflow_filename = 'workflow.cgns'
        
    def apply(self):
        
        destination = os.path.join(self.run_directory, self._workflow_filename)
        self.workflow.RunManagement['RunDirectory'] = '.'
        
        run_on_localhost = SV.run_on_localhost(self.machine, self.run_directory)
        if run_on_localhost:    
            self.workflow.set_workflow_parameters_in_tree()    
            SV.makedirs_remote(self.run_directory, machine='localhost')    
            self.workflow.write_tree(filename=destination)
            
        else:
            self._copy_files_and_update_paths_in_workflow()

            self.workflow.set_workflow_parameters_in_tree()
            self.workflow.write_tree(filename=self._workflow_filename)
            SV.copy_remote(
                source_path=self._workflow_filename, 
                destination_path=destination, 
                destination_machine=self.machine,
                )
            SV.remove_path(self._workflow_filename, machine='localhost')

    def _copy_files_and_update_paths_in_workflow(self):
        # files2copy = get_values_in_collection_from_pattern(workflow, ['*.cgns'], [])

        # TODO for now, the solution is working but it paths in the workflows are hardcoded.
        # It would be better to have a function to do:
        # for path in paths:
        #     leaf = get_leaf(workflow, path)
        #     adapt(leaf)
        #
        # path = ['RawMeshComponents', 'Source']
        # leaf = get_value_on_leaf(workflow, path)
        # if leaf.endswith('.cgns'):
        #     self.copy_file_to_data_directory(leaf)
        #     set_value_on_leaf(workflow, path, self.get_adapted_path(leaf))

        # for Component in workflow.RawMeshComponents:
        #     try:
        #         if Component['Source'].endswith('.cgns'):
        #             self.copy_file_to_data_directory(Component['Source'])
        #             Component['Source'] = self.get_adapted_path(Component['Source'])
        #     except AttributeError:
        #         pass
        
        for Component in self.workflow.RawMeshComponents:
            try:
                if Component['Source'].endswith('.cgns'):
                    self._copy_file_to_data_directory(Component['Source'])
                    Component['Source'] = self._get_adapted_path(Component['Source'])
            except AttributeError:
                pass

    def _copy_file_to_data_directory(self, path):
        machine = self.machine
        filename = path.split(os.path.sep)[-1]
        new_filename = os.path.join(self.data_directory, filename)

        if not SV.is_existing_path(new_filename, machine=machine):
            mola_logger.info(f'copy {path} to {self.data_directory}')
            SV.makedirs_remote(self.data_directory, machine=machine)
            SV.copy_remote(
                source_path=path,
                destination_path=new_filename,
                destination_machine=machine
            )
    
    def _get_adapted_path(self, path):
        filename = path.split(os.path.sep)[-1]
        dir_path = os.path.relpath(self.data_directory, start=self.run_directory)
        return os.path.join(dir_path, filename)
    



def build_loop_on_cases(sequence_of_paths, sequential_job_filename):

    loop_on_cases = f'''
SECONDS=0
SEQUENCE_OF_PATHS={sequence_of_paths}

for case in $SEQUENCE_OF_PATHS; do

    echo "entering $case"
    cd $case

    while [ ! -f "COMPLETED" ] && [ ! -f "FAILED" ]; do

        mola_prepare workflow.cgns

        echo "compute case $case at $SECONDS s"
        ./job.sh

        if [ -f "NEWJOB_REQUIRED" ]; then
            rm NEWJOB_REQUIRED
            echo "LAUNCHING THIS JOB AGAIN"
            cd ..
            sbatch {sequential_job_filename} --dependency=singleton
            exit 0
        elif [ -f "ERROR_PREPARING_WORKFLOW" ]; then
            exit 0
        fi
    done

    cd ..

done
'''
    return loop_on_cases

def set_value_on_leaf(node, path, value):
    current_path = path[0]

    if isinstance(node, Workflow):
        assert len(path) > 1
        attr = getattr(node, current_path)
        set_value_on_leaf(attr, path[1:], value)

    elif isinstance(node, dict):
        if len(path) == 1:
            node[current_path] = value
        else:
            set_value_on_leaf(node[current_path], path[1:], value)
    
    elif isinstance(node, (list, tuple)):
        if not len(path) > 1:
            raise MolaAssertionError(
                f'Path cannot end with a list (current path is {path}). '
                'You must add the key of the selected dictionary to set.'
                )
        assert current_path.count('=') == 1
        # search the good element 
        name, search_value = current_path.split('=')
        found = False
        for dico in node:
            if name in dico and str(dico[name]) == search_value:
                found = True
                break
        assert found
        set_value_on_leaf(dico, path[1:], value)
    
    else:
        raise MolaException(f'Unknown type: {type(node)}')
          
def get_value_on_leaf(node, path):
    try:
        current_path = path[0]
    except IndexError:
        return node
    
    if isinstance(node, Workflow):
        return get_value_on_leaf(getattr(node, current_path), path[1:])

    elif isinstance(node, dict):
        return get_value_on_leaf(node[current_path], path[1:])
    
    elif isinstance(node, (list, tuple)):
        assert current_path.count('=') == 1
        # search the good element 
        name, search_value = current_path.split('=')
        found = False
        for dico in node:
            if name in dico and str(dico[name]) == search_value:
                found = True
                break
        assert found
        return get_value_on_leaf(dico, path[1:])
    
    else:
        raise MolaException(f'Unknown type: {type(node)}')

def get_values_in_collection_from_key(collec, patterns, elements=[]):
    '''
    In the nested collection **collec** (may be a dictionary or a list),
    find all the values corresponding to the key **searchKey**.

    Parameters
    ----------

        collec : :py:class:`dict` or :py:class:`list`
            Nested dictionary or list where **searchKey** is searched

        searchKey : str
            Key to find in **collec**

        elements : list
            accumulated list of found values. Works as an accumulator in the
            recursive function

    Returns
    -------

        elements : list
            list of the found values correspondingto **searchKey**
    '''
    if not isinstance(patterns, list): 
        patterns = [patterns]
    
    if isinstance(collec, Workflow):
        collec = collec.convert_to_dict()
    
    if isinstance(collec, dict):
        for key, value in collec.items():
            if isinstance(value, (dict, list)):
                get_values_in_collection_from_key(value, patterns, elements=elements)
            elif any([match_pattern(key, pattern) for pattern in patterns]):
                elements.append(value)

    elif isinstance(collec, list):
        for elem in collec:
            get_values_in_collection_from_key(elem, patterns, elements=elements)

    return elements

def get_values_in_collection_from_pattern(collec, patterns, elements=[]):
    if not isinstance(patterns, list): 
        patterns = [patterns]
    
    # if isinstance(collec, Workflow):
    #     collec = collec.convert_to_dict()
    if isinstance(collec, Workflow):
        for attr_name in collec.__dict__:
            attr = getattr(collec, attr_name)
            if isinstance(attr, (dict, list)):
                get_values_in_collection_from_pattern(attr, patterns, elements=elements)

    elif isinstance(collec, dict):
        for key, value in collec.items():
            if isinstance(value, (dict, list)):
                get_values_in_collection_from_pattern(value, patterns, elements=elements)
            elif any([match_pattern(value, pattern) for pattern in patterns]):
                elements.append(value)

    elif isinstance(collec, list):
        for elem in collec:
            get_values_in_collection_from_pattern(elem, patterns, elements=elements)

    return elements

def match_pattern(value, pattern):
    if isinstance(pattern, str):
        return fnmatch(str(value), pattern) 
    elif isinstance(pattern, (int, float)):
        return value == pattern
    else:
        raise TypeError

